### PR TITLE
TIMOB-18161 Adding Java application to login into dashboard

### PR DESCRIPTION
**Pull request by pinnamur**

### CODE REVIEW

**Comment by skypanther** [comment]
**APPROVED**

**Comment by jhaynie** [comment]
what is this for?  we should not be logging in to the dashboard for Titanium. 

this needs to be reverted and removed.

@cb1kenobi @negupta

**Comment by ingo** [comment]
@jhaynie this is to implement the connection tests for https://jira.appcelerator.org/browse/TIMOB-18161. In it, we use a Java class to simulate how Studio would connect to the dashboard via a proxy. This is just the source file for the JAR we have been using in the past. It allows us (and customers) to ensure that their proxy settings are correct and has been a useful diagnostic tool. If these tests should instead be invoked via a different project, please let me know.

**Comment by jhaynie** [comment]
but we shouldn't be testing connection to the new dashboard. i'm fine with testing in general but not sure we want to hit dashboard for community going forward.

**Pull request merged**
